version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  # Expose HTTP
      - "443:443"  # Expose HTTPS
    volumes:
      - /root/arzaq-update/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the Nginx config
      - /root/arzaq-update/certs:/etc/nginx/certs:ro  # Mount the SSL certificates
    depends_on:
      - arzaq_web
    networks:
      - web_network
    restart: always

  arzaq_web:
    image: arzaq_web:latest  # Use your built image
    container_name: arzaq_web_container
    build:
      context: .  # Ensure your Dockerfile is in the current directory
    ports:
      - "3000:3000"  # Expose port 3000 to access the web app on the host
    environment:
      - DATABASE_URL=mysql://arzaq:OCloud@4.0@195.35.23.27:3306/trial_arzaq
      - BASEURL="http://localhost:3000/"
      - KINDE_ISSUER_URL=https://gshop.kinde.com
      - KINDE_SITE_URL=http://localhost:3000
      - KINDE_POST_LOGOUT_REDIRECT_URL=http://localhost:3000/
      - KINDE_POST_LOGIN_REDIRECT_URL=http://localhost:3000/
      - MAINURL=http://localhost:3000/
      - CLOUDINARY_CLOUD_NAME=dsyiarmrd
      - NEXT_PUBLIC_UPLOAD_PRESET=ARZAQ
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=331171635778625
      - CLOUDINARY_API_SECRET=NGBGQ-dAnkQgScEIq0gRff7Pdpk
      - KINDE_DOMAIN=https://gshop.kinde.com
      - KINDE_MANAGEMENT_CLIENT_ID=e6115a52df3345d99e0c993f46974a1b
      - KINDE_MANAGEMENT_CLIENT_SECRET=BGOFIXHREJxcCRxDVeaxKExJJQ2f82j0FT1NMLsJ6dCWm5X6mna6
      - KINDE_CLIENT_ID=98c6db135e7b40118cbd3f9834427b40
      - KINDE_CLIENT_SECRET=4O1xJYRVSsCXpIpvsoipRImScL7o6UOotsibKbnDyTHWJbZvdO
    networks:
      - web_network
    restart: always

networks:
  web_network:
    driver: bridge
