import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Topnavbar from "./components/navbars/Topnavbar";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Fotter from "./components/Fotter/Fotter";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { Toaster } from "@/components/ui/toaster";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { GetUsers } from "./actions/usersAction";
import { FloatingMenu } from "./components/ui/floating-dock";

export const revalidate = 1;
const nunitoSans = Open_Sans({
  subsets: ["latin"], // Include subsets you need
  weight: ["400", "700"], // Specify font weights you need
  display: "swap", // Recommended for Google Fonts
});

export const metadata: Metadata = {
  title: "ARZAQ",
  description: "Generated by create next appppssddds",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const dir = locale === "ar" ? "rtl" : "ltr";
  const { getUser } = getKindeServerSession();
  const user = await getUser();

  const getUsers = await GetUsers(user?.id);

  const users = {
    id: getUsers?.id as number,
    email: getUsers?.email ?? "",
    family_name: getUsers?.name ?? "",
    given_name: getUsers?.name ?? "",
    picture: getUsers?.avatarUrl ?? "",
    username: getUsers?.name ?? undefined,
    phone_number: getUsers?.phoneNumber ?? undefined,
  };

  const messages = await getMessages();

  return (
    <html lang={locale} dir={dir}>
      <body className={`${nunitoSans.className} bg-gray-100`}>
        {" "}
        <NextIntlClientProvider messages={messages}>
          <div className="bg-white ">
            <Topnavbar user={users} />
          </div>
          {children}
          <Analytics />
          <SpeedInsights />
          <Fotter />
        </NextIntlClientProvider>
        <FloatingMenu />
        <Toaster />
      </body>
    </html>
  );
}
